builds:
  - binary: cli53
    main: ./cmd/cli53
    ldflags: -s -w -X=github.com/barnybug/cli53.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
archives:
- name_template: "{{ .ProjectName }}-{{ if eq .Os \"darwin\" }}mac{{ else }}{{ .Os }}{{ end }}-{{ .Arch }}"
  format: binary
