name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12

    - name: Check out code
      uses: actions/checkout@v1

    - name: Run unit tests
      run: make test-unit
      
    - name: Run test coverage
      run: |
        # gucumber only works from under GOPATH...
        export GOPATH=$(go env GOPATH)
        export PATH=$PATH:$GOPATH/bin
        export GOSRC=$GOPATH/src/github.com/$GITHUB_REPOSITORY
        export GO111MODULE=on
        mkdir -p $GOSRC
        cp -r $(pwd)/* $GOSRC
        cd $GOSRC
        make test-coverage
